server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loandb?createDatabaseIfNotExist=true
    username: root
    password: 6290
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


resilience4j:
  circuitbreaker:
    instances:
      BANK-MICROSERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      CUSTOMER-MICROSERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


resilience4j.retry:
  instances:
    CUSTOMER-MICROSERVICE:
      maxAttempts: 3
      waitDuration: 2000ms
      retryExceptions:
        - feign.FeignException
        - java.net.ConnectException
    BANK-MICROSERVICE:
      maxAttempts: 3
      waitDuration: 2000ms
      retryExceptions:
        - feign.FeignException
        - java.net.ConnectException